site_name: Docs-Automation

theme:
  name: material
  palette:
    - scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
      primary: teal
      accent: teal
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
      primary: teal
      accent: teal

nav:
  - Home: index.md
  - CodeReference: code/index.html

repo_url: https://github.com/aiyu-ayaan/Docs-Automation
repo_name: Docs-Automation

plugins:
  - markdownextradata: { }

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://www.github.com/aiyu-ayaan
    - icon: fontawesome/brands/instagram
      link: https://www.instagram.com/aiyu.exe_
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/aiyu/
  version:
    stable: v1
    pre_release: v2
