name: Generate Docs and Deploy to GitHub Pages

on:
  workflow_dispatch:
    inputs:
      stable:
        description: 'Current App Stable Version'
        required: true
        default: 'v5.0.2'
      pre_release:
        description: 'Current App Pre-Release Version'
        required: true
        default: 'v5.0.3-beta'
defaults:
  run:
    working-directory: .
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Make gradlew executable
        run: chmod +x gradlew
      - name: Generate Dokka docs
        run: ./gradlew dokkaHtml
      - name: List dis
        run: ls -la
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: kt-docs
          path: build/dokka
          retention-days: 1
      - name: Upload MkDocs
        uses: actions/upload-artifact@v2
        with:
          name: mkdocs
          path: docs
          retention-days: 1

  copycode:
    runs-on: ubuntu-latest
    permissions: write-all
    needs: build
    steps:
      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: kt-docs
      - name: Download MkDocs
        uses: actions/download-artifact@v3
        with:
          name: mkdocs
      - name: Copy docs
        run: |
          ls -la
          mkdir -p copyDoc/generated
          cp mkdocs.yml copyDoc/generated
          mkdir -p copyDoc/generated/docs
          cp -r docs/* copyDoc/generated/docs
          mkdir -p copyDoc/generated/docs/code
          cp -r html/* copyDoc/generated/docs/code
          ls -la copyDoc
      - name: Upload docs
        uses: actions/upload-artifact@v2
        with:
          name: copyDoc
          path: copyDoc
          retention-days: 1
  deploy:
    runs-on: ubuntu-latest
    needs: copycode
    permissions: write-all
    steps:
      - uses: actions/checkout@v4
      - name: Configure Git Credentials
        run: |
          git config user.name github-actions[bot]
          git config user.email 41898282+github-actions[bot]@users.noreply.github.com
      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'
      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v3
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Download docs
        uses: actions/download-artifact@v3
        with:
          name: copyDoc
      - run: |
          cd generated
          pip install mkdocs-material
          pip install mkdocs-glightbox
          pip install mkdocs-markdownextradata-plugin
      - run: |
          cd generated
          sed -E 's/stable.+/stable: ${{ github.event.inputs.stable }}/' mkdocs.yml
          sed -E 's/pre_release.+/pre_release: ${{ github.event.inputs.pre_release }}/' mkdocs.yml
          echo "stable: ${{ github.event.inputs.stable }}"
          echo "pre_release: ${{ github.event.inputs.pre_release }}"
          cat mkdocs.yml
          mkdocs gh-deploy --force





