name: Release Info

on:
  push:
    branches:
      - master

jobs:
  Generated:
    runs-on: ubuntu-latest
    steps:
      - id: fetch-latest-release
        uses: kaliber5/action-get-release@v1
        with:
          github_token: ${{ github.token }}
      - name: Print Details
        run: |
          echo ${{ steps.fetch-latest-release.outputs.tag_name }}