name: Release Info

on:
  push:
    branches:
      - master

jobs:
  Generated:
    runs-on: ubuntu-latest
    steps:
      - uses: cardinalby/git-get-release-action@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          prerelease: true
      - name: Print Details
        run: |
          echo ${{ steps.latest_release.outputs.tag_name }}