name: Release Info

on:
  push:
    branches:
      - master

jobs:
  Generated:
    runs-on: ubuntu-latest
    steps:
      - name: Get latest release of NodeJS
        uses: rez0n/actions-github-release@main
        id: node_release
        with:
          token: ${{ secrets.ACCOUNT_TOKEN }}
          repository: "nodejs/node"
          type: "stable"
      - name: Get latest release of NodeJS
        run: |
          echo ${{ steps.node_release.outputs.release }}